### ISSUE TITLE
Match multiple occurrences of word in sentence

### ISSUE THREAD

**Issue by MrPiethon** [HelenFoster/JSentenceHighlighter#3]
Here is an example of the issue:

<img src="https://i.imgur.com/0CqXGvV.png"/>

We can see that it is matching the first occurrence of the word, and then stops searching.

**Comment by HelenFoster** [comment]
I vaguely remember doing that, but not sure if there was a reason. I see your point so will look into it.

**Comment by HelenFoster** [comment]
Done in 01a5ccd . (I think the reason for doing it the other way was just that it was easier.) Needs `matchAll = True` in the config file. `False` should give almost the old behaviour, except it doesn't report any more whether word 1 or word 2 was matched.
