### ISSUE TITLE
Highlighting only one card from the browser doesn't save the update

### ISSUE THREAD

**Issue by gajewsk2** [HelenFoster/JSentenceHighlighter#6]
Just experienced an odd bit of behavior. If you have only one card from the browser selected and run JSH it doesn't save the update. Throw 2 at it at once, and it's ok.

**Comment by HelenFoster** [comment]
I see it too. I'm guessing that having the fields open for editing in the browser is blocking the update.

**Comment by HelenFoster** [comment]
Confirmed that Japanese Support doesn't have this problem, so I probably just need to check how that handles it.
